Repository mitodl/ocw-hugo-themes, pull requests merged in 2021-09, with the labels that each got.

#162 ocw studio structure adjustments
  course/layouts/course/course_home.html
  course/layouts/home.html
  course/layouts/pages/baseof.html
  course/layouts/pages/instructor_insights.html
  course/layouts/pages/pdf.html
  course/layouts/pages/single.html
  course/layouts/pages/video.html
  course/layouts/pages/videogallery.html
  package.json
  yarn.lock
Labels: waiting on author, blocker

#165 use level text and search url
  www/layouts/partials/home_course_cards.html
Labels: waiting on author

#167 add templates to render instructor static JSON API responses
  base-theme/layouts/_default/baseof.json.json
  base-theme/layouts/_default/list.json.json
  base-theme/layouts/_default/single.json.json
  www/layouts/instructor/item.json.json
Labels: needs review

#164 Disable autoplay
  course/layouts/partials/youtube_player.html
Labels: needs review

#171 ocw-course not course
  .env.example
  .github/workflows/deploy.yml
  www/layouts/partials/home_course_cards.html
Labels: waiting on author

#176 fix home course card links
  www/layouts/partials/home_course_cards.html
Labels: needs review

#183 Add joining slash if none exists to course feature urls
  course/layouts/partials/course_feature.html
Labels: needs review

#186 instructors from static api
  README.md
  course/layouts/partials/course_info.html
  course/layouts/partials/course_instructor_number.html
  course/layouts/partials/get_instructors.html
  example_configs/example.course.config.toml
  package.json
  yarn.lock
Labels: waiting on author

#185 Add shortcode for resource links
  course/layouts/shortcodes/resource_link.html
Labels: needs review

#192 more ocw-studio updates
  course/data/departments.json
  course/data/search_query_keys.json
  course/layouts/home.html
  course/layouts/partials/course_feature.html
  course/layouts/partials/course_info.html
  course/layouts/partials/desktop_course_info.html
  course/layouts/partials/get_departments.html
  course/layouts/partials/get_search_url.html
  course/layouts/partials/learning_resource_type.html
  course/layouts/partials/learning_resource_types.html
  course/layouts/partials/mobile_course_info.html
  course/layouts/partials/title.html
  package.json
  yarn.lock
Labels: needs review

#172 Resource page template
  .gitignore
  course/assets/css/course.scss
  course/assets/css/download-page.scss
  course/layouts/_default/baseof.html
  course/layouts/pages/pdf.html
  course/layouts/pages/video.html
  course/layouts/pages/videogallery.html
  course/layouts/partials/download_page.html
  course/layouts/partials/video.html
  course/layouts/resources/single.html
  course/layouts/shortcodes/resource.html
  package.json
  www/layouts/_default/baseof.html
  yarn.lock
Labels: needs review

#196 check instructors before use
  course/layouts/partials/course_info.html
Labels: waiting on author

#197 Handle empty topics
  course/layouts/partials/topics.html
Labels: needs review

#200 fix inpanel
  course/layouts/partials/course_info.html
Labels: waiting on author

#202 default subtopics to an empty slice
  course/layouts/partials/topic.html
Labels: waiting on author

#207 fix home course cards topics
  www/layouts/partials/topics_summary.html
Labels: waiting on author

#205 Update ocw-to-hugo to fix typo bug
  package.json
  yarn.lock
Labels: needs review
