Repository mitodl/ocw-hugo-themes, pull requests merged in 2021-05, with the labels that each got.

#6 add a script for building an entire output folder from ocw-to-hugo
  .env.example
  README.md
  base-theme/layouts/partials/webpack_url.html
  build_scripts/build_all_courses.sh
Labels: blocker, needs review

#11 Parse URL to fix section handling
  package.json
  www/assets/js/lib/search.js
  www/assets/js/lib/search.test.js
  yarn.lock
Labels: waiting on author

#9 ocw-to-hugo 1.19.0
  package.json
  yarn.lock
Labels: waiting on author

#18 check if site.BaseURL is set before trying to use it
  base-theme/layouts/partials/site_root_url.html
  base-theme/layouts/partials/webpack_url.html
  example_configs/example.base.config.toml
  example_configs/example.course.config.toml
  example_configs/example.www.config.toml
Labels: waiting on author

#13 Disable collapse for instructors list
  course/layouts/partials/course_info.html
  course/layouts/partials/partial_collapse_list.html
Labels: needs review

#22 remove autotag in PR template
  .github/pull_request_template.md
Labels: waiting on author

#24 force mobile style if table width exceeds main content area
  course/assets/css/tables.scss
  course/assets/js/responsive_tables.js
Labels: needs review

#15 remove default salutation from search
  www/assets/js/components/SearchResult.js
  www/assets/js/components/SearchResult.test.js
Labels: waiting on author

#33 restore search icon
  base-theme/assets/css/header.scss
  base-theme/layouts/partials/header.html
  course/layouts/partials/extraheader.html
Labels: waiting on author

#27 Accessibility changes for carousel
  www/assets/css/home.scss
  www/layouts/partials/home_course_cards.html
  www/layouts/partials/promo-carousel.html
Labels: needs review

#39 fix responsive tables
  course/assets/css/tables.scss
Labels: needs review

#36 Add alt text
  base-theme/layouts/partials/header.html
  www/layouts/home.html
  www/layouts/partials/newsletter_signup.html
Labels: needs review

#45 fix course info table
  course/assets/css/tables.scss
  course/layouts/partials/course_info.html
Labels: waiting on author

#50 fix title tag generation
  base-theme/layouts/partials/head.html
  course/layouts/course/baseof.html
  course/layouts/partials/extrahead.html
  course/layouts/partials/title.html
  www/layouts/partials/extrahead.html
  www/layouts/partials/title.html
Labels: waiting on author

#49 Accessibility improvements for search
  course/layouts/course/baseof.html
  www/assets/css/search-filter.scss
  www/assets/js/components/SearchBox.js
  www/assets/js/components/SearchFacetItem.js
  www/assets/js/components/SearchPage.js
  www/assets/js/components/SearchResult.js
  www/layouts/search/section.html
Labels: needs review

#51 Add labels for a couple input fields
  www/layouts/home.html
  www/layouts/partials/newsletter_signup.html
Labels: needs review

#48 Update some headers to remove accessibility warning
  www/assets/css/home.scss
  www/layouts/home.html
  www/layouts/partials/home_course_cards.html
Labels: waiting on author

#44 other versions
  course/assets/css/course-home.scss
  course/layouts/course/course_home.html
  course/layouts/partials/course_features.html
  course/layouts/partials/other_versions.html
  package.json
  yarn.lock
Labels: blocked, waiting on author

#47 allow launching of an externally converted course
  .env.example
  README.md
  build_scripts/start_course.sh
Labels: waiting on author

#58 check length before rendering
  course/layouts/partials/other_versions.html
Labels: waiting on author

#60 Adjust color of notification banner and link text
  www/assets/css/notification.scss
Labels: waiting on author

#61 Add padding to search textbox
  www/assets/css/home.scss
Labels: waiting on author

#56 Tweaks to search accessibility page
  www/assets/js/components/SearchPage.js
  www/assets/js/components/SearchResult.js
Labels: waiting on author

#68 Switch to div for subscribe title
  www/layouts/home.html
Labels: needs review

#59 Update give button and adjust link size in promo carousel
  base-theme/assets/css/button.scss
  base-theme/assets/css/header.scss
  base-theme/layouts/partials/header.html
  base-theme/static/images/heart-orange.png
  base-theme/static/images/heart.png
  www/assets/css/home.scss
  www/layouts/home.html
  www/layouts/partials/promo-carousel.html
Labels: waiting on author

#75 other versions to data template
  course/layouts/course/course_home.html
  course/layouts/partials/other_versions.html
  package.json
  yarn.lock
Labels: waiting on author
