Repository mitodl/ocw-hugo-themes, pull requests merged in 2022-06, with the labels that each got.

#713 resources layout moved to base theme from courses
  base-theme/assets/css/main.scss
  base-theme/assets/js/pdf_viewer.js
  base-theme/layouts/partials/content_header.html
  base-theme/layouts/partials/image_page.html
  base-theme/layouts/partials/pdf_viewer.html
  base-theme/layouts/partials/resource_body.html
  base-theme/layouts/partials/resource_title.html
  base-theme/layouts/partials/video-expandable-tab.html
  base-theme/layouts/partials/video.html
  course/assets/course.js
  course/layouts/resources/single.html
  www/assets/css/pdf.scss
  www/assets/css/www.scss
  www/assets/www.tsx
  www/layouts/resources/single.coursedata.json
  www/layouts/resources/single.html
Labels: needs review

#721 fix: course list order maintained
  fields/layouts/home.html
  fields/layouts/subfields/single.html
  www/assets/js/LearningResources.ts
  www/assets/js/hooks/hugo_data.test.ts
  www/assets/js/hooks/hugo_data.ts
  www/assets/js/lib/util.ts
  www/layouts/collections/single.html
  www/layouts/course-lists/single.html
Labels: needs review

#709 Added setting button to control bar
  course/assets/course.js
  course/assets/css/videojs_player.scss
  course/assets/js/video_playback_speed.js
Labels: needs review

#730 compact search view
  package.json
  www/assets/css/learning-resource-card.scss
  www/assets/css/search.scss
  www/assets/js/components/SearchFilterDrawer.test.tsx
  www/assets/js/components/SearchFilterDrawer.tsx
  www/assets/js/components/SearchPage.test.tsx
  www/assets/js/components/SearchPage.tsx
  www/assets/js/components/SearchResult.test.tsx
  www/assets/js/components/SearchResult.tsx
  www/assets/js/lib/constants.ts
  www/assets/js/lib/search.ts
  www/static/images/icons/compact_ui_icon.png
  www/static/images/icons/list_ui_icon.png
  yarn.lock
Labels: needs review

#678 video player design update
  base-theme/assets/css/main.scss
  base-theme/assets/css/variables.scss
  base-theme/layouts/partials/video.html
  base-theme/layouts/partials/video_embed.html
  base-theme/layouts/partials/youtube_player.html
  course/assets/course.js
  course/assets/css/video-transcript.scss
  course/assets/css/video.scss
  course/assets/css/videojs_player.scss
  course/assets/js/video_fullscreen_toggle.js
Labels: needs review, waiting on author

#735 Fix video transcripts RESOURCE_BASE_URL
  base-theme/layouts/partials/video.html
Labels: waiting on author

#726 use new search metadata fields
  base-theme/layouts/partials/seo.html
Labels: waiting on author

#722 fixed images for ocw-www pages
  www/assets/css/pages.scss
  www/layouts/pages/single.html
Labels: waiting on author

#716 updated 404 page
  www/layouts/404.html
Labels: needs review

#727 Removes alt text
  www/assets/js/components/CourseListRow.tsx
Labels: waiting on author

#747 fix resource filter
  www/assets/js/lib/constants.ts
Labels: waiting on author

#744 make level array
  base-theme/layouts/partials/course_cards_level.html
  base-theme/layouts/partials/course_carousel_card.html
  www/assets/js/LearningResources.ts
  www/assets/js/components/CourseListRow.test.tsx
  www/assets/js/components/CourseListRow.tsx
  www/assets/js/components/SearchResult.test.tsx
  www/assets/js/components/SearchResult.tsx
  www/assets/js/factories/search.ts
Labels: waiting on author

#733 fix: catching exception while fetching PDF
  base-theme/assets/js/pdf_viewer.js
Labels: waiting on author

#728 fix: videojs-youtube lib included inside document.ready function
  base-theme/assets/types/videojs-youtube.d.ts
  course/assets/course.js
Labels: waiting on author

#743 added styles to fix title overlap
  course/assets/css/video.scss
Labels: needs review

#756 render course home page description
  base-theme/layouts/partials/seo.html
Labels: waiting on author

#734 getJSON replaced with resources.GetRemote
  base-theme/assets/index.ts
  base-theme/assets/js/sentry.js
  base-theme/layouts/partials/featured_course_cards.html
  base-theme/layouts/partials/sentry_capture_message.html
  course/layouts/partials/get_instructors.html
  fields/layouts/home.html
  fields/layouts/subfields/single.html
  www/layouts/collections/single.html
  www/layouts/course-lists/single.html
  www/layouts/partials/new_course_cards.html
  www/layouts/partials/ocw_news.html
  www/layouts/resource_collections/single.html
Labels: needs review

#741 update default URLs to match new scheme
  .env.example
  README.md
  base-theme/layouts/_default/sitemap.xml
  base-theme/layouts/partials/collection_cover_image.html
  base-theme/layouts/partials/featured_course_cards.html
  base-theme/layouts/partials/ocw_studio_base_url.html
  base-theme/layouts/partials/sitemap_domain.html
  base-theme/layouts/partials/static_api_base_url.html
  base-theme/layouts/robots.txt
  fields/layouts/home.html
  fields/layouts/subfields/single.html
  package_scripts/start_course.sh
  package_scripts/start_fields.sh
  package_scripts/start_www.sh
  www/layouts/collections/single.html
  www/layouts/course-lists/single.html
  www/layouts/home.xml
  www/layouts/partials/new_course_cards.html
  www/layouts/partials/ocw_news.html
  www/layouts/resource_collections/single.html
  www/layouts/sitemap.xml
Labels: waiting on author

#732 Added download button to control bar
  base-theme/layouts/partials/video.html
  base-theme/layouts/partials/video_embed.html
  base-theme/layouts/partials/youtube_player.html
  course/assets/course.js
  course/assets/css/videojs_player.scss
  course/assets/js/video-download-button.js
  course/assets/js/video_playback_speed.js
Labels: needs review

#767 user selected canonical URL
  base-theme/layouts/partials/seo.html
Labels: needs review

#753 feat: lists of course resources grouped by learning resource types
  base-theme/static/images/download.svg
  course/assets/css/course-resources.scss
  course/assets/css/course.scss
  course/content/learning_resource_types/_index.md
  course/layouts/learning_resource_types/taxonomy.html
  course/layouts/learning_resource_types/terms.html
  course/layouts/partials/get_resource_download_link.html
  course/layouts/partials/get_resource_thumbnail_src.html
  course/layouts/partials/no_resources_found.html
  course/layouts/partials/resource_list.html
  course/layouts/partials/resource_list_item.html
  course/layouts/partials/see_all.html
Labels: needs review

#761 search API error handling improved
  www/assets/js/lib/api.ts
  www/assets/js/lib/util.ts
Labels: needs review

#775 Added theme for resource list
  course/layouts/lists/single.html
Labels: needs review

#768 added deploy configurations for testing
  .github/workflows/deploy.yml
Labels: waiting on author

#776 fix: import order of videojs-youtube sorted
  course/assets/course.js
Labels: needs review
