Repository mitodl/ocw-hugo-themes, pull requests merged in 2022-01, with the labels that each got.

#306 add course_data.json
  course/layouts/index.coursedata.json
Labels: needs review

#313 fix instructors
  course/layouts/index.coursedata.json
Labels: needs review

#316 fix instructors error take 2
  course/layouts/index.coursedata.json
Labels: needs review

#309 feat: Educator Page
  base-theme/assets/css/font.scss
  base-theme/assets/css/main.scss
  www/assets/css/about.scss
  www/assets/css/common.scss
  www/assets/css/educator.scss
  www/assets/css/www.scss
  www/assets/js/subnav.js
  www/content/educator/_index.md
  www/layouts/about/section.html
  www/layouts/educator/section.html
  www/layouts/home.html
  www/static/images/educator/adapt-oer.jpg
  www/static/images/educator/cadogan2.png
  www/static/images/educator/chalk-radio-bg.png
  www/static/images/educator/connect.jpg
  www/static/images/educator/discover-oer-1.jpg
  www/static/images/educator/explore-reflective-practice.jpg
  www/static/images/educator/share-adaptions.jpg
  www/static/images/educator/students-discover-things-mobile.png
  www/static/images/educator/students-discover-things.png
  www/static/images/educator/you-only-really-understand.png
Labels: waiting on author

#310 feat: menu (sandwich) for mobile devices
  base-theme/assets/css/header.scss
  base-theme/layouts/partials/header.html
  course/layouts/partials/extraheader.html
Labels: needs review

#319 Fixed lighthouse accessibility issues
  www/assets/css/home.scss
  www/layouts/home.html
Labels: needs review

#326 delete a package-lock.json that snuck in here somehow
  package-lock.json
Labels: needs review

#323 fixed issue regarding box overflow
  base-theme/assets/css/header.scss
  www/assets/css/home.scss
Labels: needs review

#318 json data pages
  course/layouts/_default/baseof.coursedata.json
  course/layouts/_default/section.coursedata.json
  course/layouts/pages/single.coursedata.json
  course/layouts/partials/course_content.json
  course/layouts/partials/video-gallery-page.json
  course/layouts/resources/single.coursedata.json
  course/layouts/video_galleries/single.coursedata.json
Labels: needs review

#334 fix: removing extra font-size for h2 tag
  base-theme/assets/css/main.scss
Labels: waiting on author

#336 fix: placing mp_logo in static images of course theme
  course/static/images/mp_logo.gif
Labels: needs review

#339 add course image to coursedata.json
  course/layouts/home.html
  course/layouts/index.coursedata.json
  course/layouts/partials/course-image-url.html
Labels: needs review

#335 switch to building w/ typescript
  .github/workflows/ci.yml
  .gitignore
  README.md
  base-theme/assets/index.ts
  base-theme/assets/types/react-dotdotdot.d.ts
  base-theme/assets/types/videojs-transcript-ac.d.ts
  base-theme/assets/webpack/webpack.common.js
  course/assets/js/course_expander.test.ts
  course/assets/js/course_expander.ts
  course/assets/js/course_info_toggle.js
  course/assets/js/div_toggle.js
  course/assets/js/navigation.js
  course/assets/js/pdf_viewer.js
  course/assets/js/quiz_multiple_choice.js
  course/assets/js/responsive_tables.js
  course/assets/js/video_transcript_track.js
  jest.config.js
  package.json
  tsconfig.json
  www/assets/js/LearningResources.ts
  www/assets/js/components/Card.js
  www/assets/js/components/Card.test.tsx
  www/assets/js/components/Card.tsx
  www/assets/js/components/Facet.tsx
  www/assets/js/components/FacetDisplay.test.tsx
  www/assets/js/components/FacetDisplay.tsx
  www/assets/js/components/FilterableFacet.tsx
  www/assets/js/components/Loading.test.tsx
  www/assets/js/components/Loading.tsx
  www/assets/js/components/SearchBox.test.tsx
  www/assets/js/components/SearchBox.tsx
  www/assets/js/components/SearchFacetItem.tsx
  www/assets/js/components/SearchFilter.test.tsx
  www/assets/js/components/SearchFilter.tsx
  www/assets/js/components/SearchFilterDrawer.test.tsx
  www/assets/js/components/SearchFilterDrawer.tsx
  www/assets/js/components/SearchPage.test.tsx
  www/assets/js/components/SearchPage.tsx
  www/assets/js/components/SearchResult.test.tsx
  www/assets/js/components/SearchResult.tsx
  www/assets/js/factories/search.js
  www/assets/js/factories/search.ts
  www/assets/js/hooks/util.ts
  www/assets/js/lib/api.js
  www/assets/js/lib/api.test.ts
  www/assets/js/lib/api.ts
  www/assets/js/lib/constants.ts
  www/assets/js/lib/search.test.tsx
  www/assets/js/lib/search.ts
  www/assets/js/lib/util.ts
  www/assets/js/notification.js
  www/assets/js/subnav.ts
  www/assets/js/test_setup.ts
  www/assets/www.tsx
  yarn.lock
Labels: needs review

#330 feat: expand/collapse enhancement
  course/assets/css/course-home.scss
  course/assets/css/course-info.scss
  course/layouts/home.html
  course/layouts/partials/course_info.html
Labels: waiting on author

#348 add optional colspan and rowspan attributes to tdopen / thopen shortcodes
  base-theme/assets/css/main.scss
  base-theme/layouts/shortcodes/tdopen.html
  base-theme/layouts/shortcodes/thopen.html
Labels: waiting on author

#352 Match window pathname and href in anchor tag irrespective of trailing slash
  course/assets/js/navigation.js
Labels: needs review

#353 feat: contact page
  base-theme/assets/css/main.scss
  base-theme/layouts/partials/header.html
  www/assets/css/contact.scss
  www/assets/css/educator.scss
  www/assets/css/pages.scss
  www/assets/css/www.scss
  www/content/contact/_index.md
  www/layouts/contact/section.html
  www/static/images/contact/frequently-asked-questions.jpg
Labels: needs review

#362 fix: hide resource types when count is 0
  course/layouts/partials/learning_resource_types.html
Labels: needs review

#337 fix: horizontal scroll bar on topics in drawer
  base-theme/assets/css/main.scss
  course/assets/css/course-info.scss
  course/layouts/home.html
  course/layouts/partials/course_info.html
  course/layouts/partials/topics.html
Labels: needs review

#363 added aspect ratio to match youtubes video iframe
  base-theme/assets/css/main.scss
  www/layouts/about/section.html
  www/layouts/educator/section.html
Labels: needs review

#365 fix: adding data attributes to carousel
  www/layouts/partials/home_course_cards.html
Labels: needs review

#364 feat: expand/collapse in document title
  course/assets/css/course-content.scss
  course/assets/css/course.scss
  course/layouts/partials/course_content.html
Labels: needs review

#368 fix: carousel height and thumb swipe fixed
  www/assets/css/home.scss
  www/layouts/partials/promo-carousel.html
Labels: waiting on author

#387 populate resource title
  course/layouts/resources/single.coursedata.json
Labels: waiting on author

#371 slugify text before using it as an ID
  www/assets/js/components/SearchFacetItem.tsx
  www/assets/js/lib/util.test.ts
  www/assets/js/lib/util.ts
Labels: needs review, accessibility

#380 fix aria-live situation
  www/assets/js/components/SearchPage.test.tsx
  www/assets/js/components/SearchPage.tsx
Labels: needs review, accessibility

#381 fix up role="search" situation
  www/assets/js/components/SearchBox.test.tsx
  www/assets/js/components/SearchBox.tsx
Labels: needs review, accessibility

#374 fix some more type issues, upgrade course-search-utils
  package.json
  www/assets/js/LearningResources.ts
  www/assets/js/components/Facet.tsx
  www/assets/js/components/FacetDisplay.tsx
  www/assets/js/components/FilterableFacet.tsx
  www/assets/js/components/SearchFacetItem.tsx
  www/assets/js/components/SearchFilterDrawer.test.tsx
  www/assets/js/components/SearchFilterDrawer.tsx
  www/assets/js/components/SearchPage.test.tsx
  www/assets/js/components/SearchPage.tsx
  www/assets/js/components/SearchResult.test.tsx
  www/assets/js/components/SearchResult.tsx
  www/assets/js/factories/search.ts
  www/assets/js/lib/constants.ts
  www/assets/js/lib/search.test.tsx
  www/assets/js/lib/search.ts
  yarn.lock
Labels: needs review

#392 fix small oversight on typescript change
  package.json
Labels: needs review

#388 fix: instructor insights images scaled up
  course/assets/css/instructor-insights.scss
Labels: needs review
