Repository mitodl/ocw-hugo-themes, pull requests merged in 2022-09, with the labels that each got.

#837 Fixed responsiveness of tables in course-v2
  course-v2/assets/js/responsive_tables.js
Labels: waiting on author

#839 remove search links in offline course theme
  base-theme/layouts/partials/course_cards_instructors.html
  base-theme/layouts/partials/course_cards_level.html
  base-theme/layouts/partials/course_cards_topics.html
  base-theme/layouts/partials/link.html
  course-offline/layouts/partials/extraheader.html
  course-offline/layouts/partials/get_search_url.html
  course-v2/layouts/partials/course_info.html
  course-v2/layouts/partials/get_instructors.html
  course-v2/layouts/partials/partial_collapse_list.html
  course-v2/layouts/partials/topic.html
  course/layouts/partials/course_info.html
  course/layouts/partials/get_instructors.html
  course/layouts/partials/topic.html
  course/layouts/partials/topics_oneline.html
Labels: waiting on author

#841 fix course banner link in course-offline theme
  course-v2/layouts/_default/baseof.html
  course-v2/layouts/home.html
  course/layouts/_default/baseof.html
Labels: waiting on author

#851 collapse facets and move department to top
  www/assets/js/LearningResources.ts
  www/assets/js/components/Facet.tsx
  www/assets/js/components/FacetDisplay.test.tsx
  www/assets/js/components/FacetDisplay.tsx
  www/assets/js/components/FilterableFacet.tsx
  www/assets/js/components/SearchPage.test.tsx
  www/assets/js/components/SearchPage.tsx
Labels: waiting on author

#850 online / offline detection in offline course sites
  base-theme/assets/css/header.scss
  base-theme/layouts/partials/course_cards_instructors.html
  base-theme/layouts/partials/course_cards_level.html
  base-theme/layouts/partials/course_cards_topics.html
  base-theme/layouts/partials/footer.html
  base-theme/layouts/partials/header.html
  base-theme/layouts/partials/hide_offline_links.html
  base-theme/layouts/partials/link.html
  base-theme/layouts/partials/video.html
  base-theme/layouts/partials/video_captions_file_url.html
  base-theme/layouts/partials/video_embed.html
  base-theme/layouts/partials/video_v2.html
  course-offline/layouts/partials/get_destination.html
  course-offline/layouts/partials/get_search_url.html
  course-offline/layouts/partials/site_root_url.html
  course-offline/layouts/partials/video_captions_file_url.html
  course-v2/layouts/_default/baseof.html
  course-v2/layouts/home.html
  course-v2/layouts/partials/course_info.html
  course-v2/layouts/partials/partial_collapse_list.html
  course-v2/layouts/partials/topic.html
  course/layouts/_default/baseof.html
  course/layouts/home.html
  course/layouts/partials/course_info.html
  course/layouts/partials/topic.html
  course/layouts/partials/topics_oneline.html
Labels: needs review, waiting on author

#857 expand parent nav item when selected
  course-v2/assets/js/navigation.js
  course-v2/layouts/partials/nav_item.html
  course/assets/js/navigation.js
  course/layouts/partials/nav_item.html
Labels: waiting on author

#858 fix: new line removed
  base-theme/layouts/_default/_markup/render-link.html
Labels: needs review

#823 metadata tags added for sharing on Facebook
  base-theme/layouts/partials/course-image-url.html
  base-theme/layouts/partials/extra_metadata.html
  base-theme/layouts/partials/head.html
  base-theme/layouts/partials/seo.html
  course-v2/layouts/partials/title.html
  course/layouts/partials/title.html
  fields/layouts/partials/title.html
  www/layouts/partials/extra_metadata.html
  www/layouts/partials/title.html
Labels: waiting on author

#859 rework video_embed to properly generate links to video pages offline
  base-theme/layouts/partials/page_url.html
  base-theme/layouts/partials/video_embed.html
  base-theme/layouts/shortcodes/resource.html
  course-offline/layouts/partials/page_url.html
Labels: waiting on author

#855 add webpack bundle analyzer
  README.md
  base-theme/assets/webpack/webpack.common.js
  package.json
  yarn.lock
Labels: waiting on author

#866 bootstrap col restored
  course-v2/assets/css/course-home.scss
  course-v2/assets/css/course-image-section.scss
  course-v2/layouts/_default/baseof.html
  course-v2/layouts/home.html
Labels: needs review

#844 Fix table renders for course-v1 when table width is greater then main-content width
  course/assets/course.ts
  course/assets/js/course_info_toggle.js
  course/assets/js/responsive_tables.js
Labels: needs review

#871 fix give now link
  base-theme/layouts/partials/header.html
Labels: waiting on author
