Repository mitodl/ocw-hugo-themes, pull requests merged in 2022-11, with the labels that each got.

#942 rename /resources to /download
  course-v2/content/learning_resource_types/_index.md
  course-v2/content/resources/_index.md
Labels: waiting on author

#944 Resizing download button layout for mobile
  course-v2/layouts/partials/resources_header.html
Labels: needs review

#903 fix: sentry DSN configured via env
  .eslintrc
  base-theme/assets/js/sentry.ts
Labels: waiting on author

#954 build webpack once, not thrice
  .github/workflows/deploy.yml
Labels: waiting on author

#953 Ab/set compact UI live
  package.json
  www/assets/css/learning-resource-card.scss
  www/assets/css/search.scss
  www/assets/js/components/SearchFilterDrawer.tsx
  www/assets/js/components/SearchPage.test.tsx
  www/assets/js/components/SearchPage.tsx
  www/assets/js/lib/constants.ts
  yarn.lock
Labels: needs review

#960 only show download button if zip exists
  course-v2/layouts/partials/resources_header.html
Labels: waiting on author

#941 set up e2e tests with playwright
  .env.example
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .gitignore
  .nvmrc
  README.md
  base-theme/assets/webpack/webpack.dev.ts
  base-theme/layouts/partials/webpack_url.html
  course-v2/layouts/partials/course_detail.html
  jest.config.js
  package.json
  package_scripts/build.sh
  package_scripts/build_all_courses.sh
  package_scripts/common.sh
  package_scripts/import_courses.sh
  package_scripts/start_course.sh
  package_scripts/start_fields.sh
  package_scripts/start_www.sh
  playwright.config.ts
  test-sites/ocw-ci-test-course/README.md
  test-sites/ocw-ci-test-course/config/_default/menus.yaml
  test-sites/ocw-ci-test-course/content/pages/assignments.md
  test-sites/ocw-ci-test-course/content/pages/first-test-page-title.md
  test-sites/ocw-ci-test-course/content/pages/second-test-page.md
  test-sites/ocw-ci-test-course/content/pages/section-1.md
  test-sites/ocw-ci-test-course/content/pages/shortcode-demos.md
  test-sites/ocw-ci-test-course/content/pages/subsection-1a.md
  test-sites/ocw-ci-test-course/content/pages/subsection-1b.md
  test-sites/ocw-ci-test-course/content/resources/example_jpg.md
  test-sites/ocw-ci-test-course/content/resources/example_pdf.md
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l01v01_360p.md
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l01v02_360p.md
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l01v03_360p.md
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l01v04_360p.md
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l01v05_360p.md
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l26v01_360p.md
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l26v02_360p.md
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l26v03_360p.md
  test-sites/ocw-ci-test-course/data/course.json
  test-sites/ocw-ci-test-www/README.md
  tests-e2e/README.md
  tests-e2e/global-setup.ts
  tests-e2e/ocw-ci-test-course/homepage.spec.ts
  tests-e2e/ocw-ci-test-course/shortcodes.spec.ts
  tests-e2e/ocw-ci-test-www/homepage.spec.ts
  tests-e2e/util/CoursePage.ts
  tests-e2e/util/index.ts
  tests-e2e/util/locators.ts
  tests-e2e/util/test_sites.ts
  yarn.lock
Labels: needs review

#965 rename OCW_IMPORT_STARTER_SLUG to OCW_COURSE_STARTER_SLUG
  .env.example
  .github/workflows/deploy.yml
  README.md
  www/layouts/partials/new_course_cards.html
Labels: needs review, blocked

#967 fix: typo in footer
  base-theme/layouts/partials/footer-v2.html
Labels: waiting on author

#964 Clean up env variables + make them all optional
  .env.example
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .prettierignore
  .prettierrc.yaml
  .prettierrc.yml
  README.md
  base-theme/assets/webpack/webpack.dev.ts
  base-theme/layouts/partials/webpack_url.html
  env.ts
  jest.config.js
  package.json
  package_scripts/build.sh
  package_scripts/build_all_courses.sh
  package_scripts/common.sh
  package_scripts/import_courses.sh
  package_scripts/start_course.sh
  package_scripts/start_fields.sh
  package_scripts/start_www.sh
  package_scripts/with-env.ts
  playwright.config.ts
  postcss.config.js
  tests-e2e/global-setup.ts
  tests-e2e/util/test_sites.ts
  tsconfig.json
  yarn.lock
Labels: needs review, blocked

#975 improve start course, start www, start fields
  README.md
  env.ts
  package.json
  package_scripts/start.ts
  package_scripts/start_course.sh
  package_scripts/start_fields.sh
  package_scripts/start_www.sh
  package_scripts/util.ts
  yarn.lock
Labels: needs review

#979 hide download button if zip doesn't exist v2
  course-v2/layouts/partials/resources_header.html
Labels: needs review

#981 Update Prettier for better TS support.
  course-v2/assets/js/video_playback_speed.js
  course/assets/js/course_info_toggle.ts
  course/assets/js/video_playback_speed.js
  env.ts
  package.json
  www/assets/js/components/Card.tsx
  www/assets/js/components/Facet.tsx
  www/assets/js/components/FilterableFacet.tsx
  www/assets/js/components/SearchPage.test.tsx
  www/assets/js/components/SearchResult.test.tsx
  www/assets/js/lib/search.test.tsx
  yarn.lock
Labels: waiting on author

#966 add course download page link button
  base-theme/layouts/partials/file_exists_at_url.html
  course-v2/assets/css/course-image-section.scss
  course-v2/assets/css/course-info.scss
  course-v2/assets/css/course-resources.scss
  course-v2/layouts/learning_resource_types/taxonomy.html
  course-v2/layouts/partials/course_image_section.html
  course-v2/layouts/partials/desktop_course_info.html
  course-v2/layouts/partials/download_course_link_button.html
  course-v2/layouts/partials/get_course_download_url.html
  course-v2/layouts/partials/mobile_course_info.html
  course-v2/layouts/partials/resources_header.html
  course-v2/layouts/partials/show_no_resources_found.html
Labels: waiting on author

#969 Replaced hugo {{ }} tag with {{- -}}
  base-theme/layouts/partials/course_cards_instructors.html
  base-theme/layouts/partials/course_cards_level.html
  base-theme/layouts/partials/course_cards_topics.html
  base-theme/layouts/partials/link.html
  course-v2/layouts/partials/course_info.html
  course-v2/layouts/partials/partial_collapse_list.html
  course-v2/layouts/partials/topic.html
  course/layouts/partials/course_info.html
  course/layouts/partials/topic.html
  course/layouts/partials/topics_oneline.html
  www/layouts/partials/staff_card.html
Labels: needs review

#961 fix: expand/collapse arrow removed and full title shown
  base-theme/layouts/partials/content_header_v2.html
  course-v2/layouts/partials/course_content.html
Labels: needs review

#992 Updating text on Educator page
  www/layouts/educator/section.html
Labels: waiting on author

#1000 hide text about video / audio materials if they aren't detected
  course-v2/layouts/partials/contains_videos.html
  course-v2/layouts/partials/resources_header.html
Labels: waiting on author

#984 Display time on single line, don't clash with vol
  course-v2/assets/css/videojs_player.scss
  course/assets/css/videojs_player.scss
Labels: waiting on author

#1001 Better isolate e2e sites from RC + add featured courses
  .gitignore
  env.ts
  package.json
  package_scripts/start.ts
  package_scripts/util.ts
  test-sites/__fixtures__/README.md
  test-sites/__fixtures__/courses/ocw-ci-test-course/data.json
  test-sites/__fixtures__/ocw-ci-test-www/instructors/3caa0884-4fdd-4f3c-ba39-67a64c27d877/index.json
  test-sites/__fixtures__/ocw-ci-test-www/instructors/588e4e64-823f-4e8e-a29e-0e695e2297ae/index.json
  test-sites/__fixtures__/ocw-ci-test-www/instructors/d3c64374-bb1c-46bb-a1a1-827c336e4d8e/index.json
  test-sites/ocw-ci-test-course/data/course.json
  test-sites/ocw-ci-test-www/content/course-lists/featured-courses-homepage.md
  test-sites/ocw-ci-test-www/content/instructors/3caa0884-4fdd-4f3c-ba39-67a64c27d877.md
  test-sites/ocw-ci-test-www/content/instructors/588e4e64-823f-4e8e-a29e-0e695e2297ae.md
  test-sites/ocw-ci-test-www/content/instructors/d3c64374-bb1c-46bb-a1a1-827c336e4d8e.md
  tests-e2e/fixtures.spec.ts
  tests-e2e/global-setup.ts
  tests-e2e/ocw-ci-test-course/homepage.spec.ts
  tests-e2e/ocw-ci-test-course/shortcodes.spec.ts
  tests-e2e/ocw-ci-test-www/featured_courses.spec.ts
  tests-e2e/util/SimpleServer.ts
  tests-e2e/util/WwwPage.ts
  tests-e2e/util/index.ts
  tests-e2e/util/locators.ts
  tests-e2e/util/test_sites.ts
  yarn.lock
Labels: needs review
