Repository mitodl/ocw-hugo-themes, pull requests merged in 2022-02, with the labels that each got.

#367 Wassaf/341 newsletter page
  base-theme/assets/css/variables.scss
  www/assets/css/newsletter.scss
  www/assets/css/www.scss
  www/assets/js/lib/util.ts
  www/assets/js/mailchimp.js
  www/content/newsletter/_index.md
  www/layouts/newsletter/section.html
  www/layouts/partials/extrahead.html
  www/layouts/partials/newsletter_signup.html
Labels: waiting on author

#344 add course collection display
  README.md
  package.json
  www/assets/js/LearningResources.ts
  www/assets/js/components/CourseCollection.test.tsx
  www/assets/js/components/CourseCollection.tsx
  www/assets/js/components/SearchResult.tsx
  www/assets/js/factories/search.ts
  www/assets/js/hooks/course_collection.test.ts
  www/assets/js/hooks/course_collection.ts
  www/assets/js/lib/search.test.tsx
  www/assets/js/lib/search.ts
  www/assets/www.tsx
  www/layouts/course_collections/single.html
  yarn.lock
Labels: needs review

#389 fix: accessibility fixes
  base-theme/assets/css/main.scss
  www/assets/css/common.scss
  www/assets/css/educator.scss
  www/layouts/educator/section.html
  www/static/images/educator/share-adaptations.jpg
Labels: needs review, accessibility

#408 fix: alt text removed for lecture videos
  course/layouts/partials/video-gallery-item.html
Labels: needs review

#400 add a data template for creating a course content map
  course/layouts/index.contentmap.json
Labels: waiting on author

#397 added section to course theme
  course/layouts/pages/section.html
Labels: waiting on author

#343 Wassaf/28 ocw hugo footer
  base-theme/assets/css/bootstrap-overrides.scss
  base-theme/assets/css/footer.scss
  base-theme/assets/css/main.scss
  base-theme/assets/css/variables.scss
  base-theme/layouts/partials/footer.html
  base-theme/static/images/Facebook.png
  base-theme/static/images/Instagram.png
  base-theme/static/images/LinkedIn.png
  base-theme/static/images/MIT-logo-red-gray-54x28.svg
  base-theme/static/images/Twitter.png
  base-theme/static/images/Youtube.png
  base-theme/static/images/mit-logo-black-red.svg
  base-theme/static/images/mit-logo-red.svg
  base-theme/static/images/mit-ol.png
  base-theme/static/images/oeg_logo.png
  www/layouts/about/section.html
  www/layouts/contact/section.html
  www/layouts/educator/section.html
  www/layouts/home.html
Labels: waiting on author

#417 accessibility: about page
  www/assets/css/about.scss
  www/layouts/about/section.html
Labels: needs review

#416 accessibility: home page
  base-theme/layouts/partials/footer.html
  www/assets/css/home.scss
  www/layouts/contact/section.html
  www/layouts/home.html
  www/layouts/partials/home_course_cards.html
  www/layouts/partials/home_testimonials.html
  www/layouts/partials/newsletter_signup.html
  www/layouts/partials/ocw_news.html
  www/layouts/partials/promo-carousel.html
  www/layouts/testimonials/list.html
  www/layouts/testimonials/single.html
Labels: needs review

#423 Fixed typo which is causing link to be broken
  base-theme/layouts/partials/footer.html
Labels: needs review

#407 fix: increased value for expand widget for course image description
  course/layouts/home.html
Labels: needs review

#411 Add course collection partial
  base-theme/assets/css/variables.scss
  www/assets/css/course-collection.scss
  www/assets/css/www.scss
  www/layouts/home.html
  www/layouts/partials/home_course_collections.html
Labels: waiting on author

#427 fix: some margin bottom added below course description
  course/layouts/home.html
Labels: needs review

#431 fixed bug with boldsymbol not rendering
  base-theme/assets/webpack/webpack.common.js
Labels: waiting on author

#425 added course info button to tab order
  course/assets/js/course_info_toggle.js
  course/layouts/_default/baseof.html
Labels: waiting on author

#434 properly format urls passed into `resource_file.html`
  course/layouts/shortcodes/resource_file.html
Labels: needs review

#440 scoped css to prevent side-effects
  course/assets/css/instructor-insights.scss
  course/layouts/partials/course_content.html
Labels: waiting on author

#439 removed focus causing the page to scroll down
  www/assets/js/mailchimp.js
Labels: waiting on author

#358 Minor readme updates
  .env.example
  README.md
Labels: waiting on author

#438 fixed resource toggling issue
  www/assets/js/components/SearchPage.tsx
Labels: needs review

#442 fix: moving logo from course static to base static
  base-theme/static/images/mp_logo.gif
Labels: needs review

#445 fixed video urls not linking to archive.org
  base-theme/layouts/partials/resource_url.html
  course/layouts/partials/video.html
  course/layouts/partials/video_embed.html
Labels: waiting on author

#452 fix: style of h3 in td, name of an id changed
  course/assets/css/course-content.scss
  course/assets/css/instructor-insights.scss
  course/layouts/partials/course_content.html
Labels: needs review

#473 moved resource link to base theme
  base-theme/layouts/shortcodes/resource_link.html
Labels: waiting on author

#470 Fixed CSS for image rendering small
  base-theme/assets/css/main.scss
Labels: needs review

#468 Fixed page_title partial caching the Title
  www/layouts/pages/single.html
Labels: waiting on author

#456 Redesigned footer
  base-theme/assets/css/footer.scss
  base-theme/layouts/partials/footer.html
  base-theme/static/images/Youtube.png
Labels: waiting on author

#467 Added footer to Pages Template
  www/layouts/pages/single.html
Labels: waiting on author
