Repository mitodl/ocw-hugo-themes, pull requests merged in 2023-07, with the labels that each got.

#1168 OCW News Redesign
  base-theme/assets/css/_breakpoints.scss
  base-theme/assets/css/variables.scss
  base-theme/assets/images/default_news.png
  www/assets/css/home.scss
  www/layouts/partials/ocw_news.html
Labels: waiting on author

#1185 replace all instances of window.onload with addEventListener
  base-offline/layouts/shortcodes/image-gallery.html
  base-theme/layouts/partials/local_video_player.html
  base-theme/layouts/partials/youtube_player.html
  base-theme/layouts/shortcodes/image-gallery.html
  www-offline/layouts/search/section.html
Labels: waiting on author, product:ocw

#1184 Change OCW News mobile(xs) display to horizontal
  base-theme/assets/css/variables.scss
  www/assets/css/home.scss
Labels: waiting on author, product:ocw

#1183 adjust fuse threshold in offline search to better filter out irrelevant results
  www-offline/layouts/search/section.html
Labels: needs review, product:ocw

#1191 Optimize imports using global flag variable to ensure videojs and nanogallery are loaded once only
  course-v2/assets/course-v2.ts
Labels: waiting on author

#1195 fix offline video player for videos with no archive_url
  base-offline/layouts/partials/video.html
  base-offline/layouts/partials/video_player.html
Labels: waiting on author, product:ocw

#1188 fix: broken offline course images
  base-theme/layouts/partials/image_resource.html
Labels: waiting on author

#1201 Improve request parallelization, particularly on Chrome
  base-theme/layouts/partials/head.html
Labels: needs review

#1207 Course theme accessibility fixes (aria-hidden and aria-expanded)
  base-theme/layouts/partials/resource_body_v2.html
  course-v2/layouts/partials/learning_resource_type.html
  course-v2/layouts/partials/resource_list_collapsible.html
  course-v2/layouts/partials/resource_list_item.html
  course-v2/layouts/partials/resources_header.html
  course-v2/layouts/partials/see_all.html
  course-v2/layouts/partials/topic.html
Labels: waiting on author
