Repository mitodl/ocw-hugo-themes, pull requests merged in 2023-01, with the labels that each got.

#1017 Test build failures
  .github/workflows/ci.yml
  .gitignore
  jest.config.ts
  package.json
  package_scripts/util.ts
  playwright.config.ts
  tests-e2e/LocalOcw.ts
  tests-e2e/global-setup.ts
  tests-e2e/jest/build-failures.test.ts
  yarn.lock
Labels: needs review

#1027 Cc/disallow failed requests
  base-theme/layouts/partials/featured_course_cards.html
  course-v2/layouts/partials/get_instructors.html
  env.ts
  test-sites/__fixtures__/api/websites.json
  test-sites/__fixtures__/courses/ocw-ci-test-course/data.json
  test-sites/__fixtures__/courses/some-featured-course/data.json
  test-sites/__fixtures__/courses/some-new-course/data.json
  test-sites/ocw-ci-test-www/content/course-lists/featured-courses-homepage.md
  tests-e2e/LocalOcw.ts
  tests-e2e/fixtures.spec.ts
  tests-e2e/global-setup.ts
  tests-e2e/jest/build-failures.test.ts
  tests-e2e/ocw-ci-test-www/featured_courses.spec.ts
  tests-e2e/util/WwwPage.ts
  www/layouts/partials/new_course_cards.html
Labels: needs review

#1028 display 12 new courses, not 10
  www/layouts/partials/new_course_cards.html
Labels: waiting on author

#1042 produce source-maps in prod build
  base-theme/assets/webpack/webpack.prod.ts
  tsconfig.json
Labels: waiting on author

#1046 remove unused "Coming Soon" code
  base-theme/assets/css/main.scss
  base-theme/assets/index.ts
  course-v2/layouts/partials/partial_collapse_list.html
  package.json
  www/assets/www.tsx
  yarn.lock
Labels: waiting on author

#1044 better tree-shaking... compile ts to ESM (before bundling)
  tsconfig.json
Labels: needs review, waiting on author

#1048 add pre-commit config
  .pre-commit-config.yaml
  .secrets.baseline
Labels: waiting on author

#1054 remove manual, redundant inclusion of 4 deps bundled with nanogallery2
  base-theme/assets/index.ts
  base-theme/assets/webpack/webpack.common.ts
  package.json
  www/assets/www.tsx
  yarn.lock
Labels: waiting on author

#1053 Updated promo carousel to handle featured promos
  base-theme/layouts/partials/filtered_pages.html
  www/layouts/partials/promo-carousel.html
Labels: waiting on author

#879 Updated error message
  www/layouts/collections/single.html
Labels: waiting on author

#1059 Deduplicate webpack assets
  base-theme/assets/index.ts
  base-theme/assets/webpack/webpack.common.ts
  base-theme/layouts/partials/head.html
  base-theme/layouts/partials/include_css.html
  base-theme/layouts/partials/include_js.html
  course-v2/assets/course-v2.ts
  course-v2/assets/instructor-insights.js
  course-v2/layouts/_default/baseof.html
  course-v2/layouts/home.html
  course-v2/layouts/partials/extrahead.html
  fields/layouts/_default/baseof.html
  fields/layouts/partials/extrahead.html
  fields/layouts/partials/extrajs.html
  playwright.config.ts
  www/layouts/_default/baseof.html
  www/layouts/partials/extrahead.html
  www/layouts/partials/extrajs.html
Labels: waiting on author

#1067 team listing updated: Jennifer Carter added
  www/content/staff/jennifer-carter.md
  www/static/images/about/staff/jennifer-carter.jpg
Labels: waiting on author
