Repository mitodl/ocw-hugo-themes, pull requests merged in 2023-05, with the labels that each got.

#1138 pass page context to video_expandable_tab wherever it's used
  base-theme/layouts/partials/video.html
  base-theme/layouts/partials/video_embed.html
  base-theme/layouts/partials/video_expandable_tab.html
  package.json
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l01v01_360p.md
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l01v02_360p.md
  tests-e2e/ocw-ci-test-course/video-tabs.spec.ts
  tests-e2e/ocw-ci-test-www/featured_courses.spec.ts
  tests-e2e/util/VideoElement.ts
  tests-e2e/util/WwwPage.ts
  yarn.lock
Labels: needs review

#1144 fix course-offline image gallery bug
  base-theme/layouts/shortcodes/image-gallery.html
Labels: waiting on author

#1135 feat: keyboard navigable video buttons
  base-theme/assets/css/video.scss
  base-theme/layouts/partials/video_expandable_tab.html
  base-theme/layouts/partials/video_tab_title.html
  course-v2/assets/course-v2.ts
  course-v2/assets/css/video.scss
  course-v2/assets/videojs-imports.js
  package.json
  test-sites/ocw-ci-test-course/config/_default/menus.yaml
  test-sites/ocw-ci-test-course/content/pages/video-series-overview.md
  test-sites/ocw-ci-test-course/content/resources/example_notes.md
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l01v01_360p.md
  tests-e2e/ocw-ci-test-course/video-tabs.spec.ts
  yarn.lock
Labels: waiting on author

#1139 Playwright video tests added - Start/End time - Transcript time
  test-sites/ocw-ci-test-course/content/resources/ocw_test_course_mit8_01f16_l01v01_360p.md
  tests-e2e/ocw-ci-test-course/video.spec.ts
  tests-e2e/util/VideoElement.ts
  tests-e2e/util/index.ts
Labels: waiting on author

#1156 disable bundle splitting in offline sites
  base-offline/layouts/shortcodes/image-gallery.html
  base-theme/assets/webpack/webpack.common.ts
  course-offline/assets/course-offline.ts
  course-offline/layouts/partials/basejs.html
  course-offline/layouts/partials/extrahead.html
  course-offline/layouts/partials/extrajs.html
  course-offline/layouts/partials/resource_url.html
  course-v2/layouts/_default/baseof.html
  course-v2/layouts/partials/basejs.html
  course-v2/layouts/partials/extrajs.html
Labels: waiting on author, product:ocw

#1147 replace <div> with semantic heading tags in course theme
  course-v2/assets/css/course-info.scss
  course-v2/assets/css/course-v2.scss
  course-v2/layouts/partials/course_banner.html
  course-v2/layouts/partials/course_description.html
  course-v2/layouts/partials/course_info.html
  course-v2/layouts/partials/learning_resource_types.html
  course-v2/layouts/partials/topics.html
  test-sites/ocw-ci-test-course/content/pages/assignments.md
  tests-e2e/ocw-ci-test-course/headings.spec.ts
Labels: needs review

#1149 fix: non-pdf files show pdf thumbnail
  course-v2/layouts/partials/get_resource_thumbnail_attributes.html
  course-v2/layouts/partials/get_resource_thumbnail_src.html
  course-v2/layouts/partials/resource_list_item.html
  course-v2/layouts/partials/resource_list_item_title.html
  test-sites/ocw-ci-test-course/config/_default/menus.yaml
  test-sites/ocw-ci-test-course/content/lists/a-resource-list.md
  test-sites/ocw-ci-test-course/content/resources/file_docx.md
  test-sites/ocw-ci-test-course/content/resources/file_mp4.md
  test-sites/ocw-ci-test-course/content/resources/file_pdf.md
  test-sites/ocw-ci-test-course/content/resources/file_png.md
  test-sites/ocw-ci-test-course/content/resources/file_py.md
  test-sites/ocw-ci-test-course/content/resources/file_txt.md
  tests-e2e/ocw-ci-test-course/resource-list.spec.ts
Labels: waiting on author

#1159 Deprecation Warning Fixes and Dependency Updates
  .github/workflows/deploy.yml
  util/formatLighthouseComment.js
Labels: waiting on author
