Repository mitodl/ocw-hugo-themes, pull requests merged in 2023-10, with the labels that each got.

#1246 fix mobile layout responsiveness for video resources
  course-v2/assets/css/video.scss
  course-v2/layouts/partials/video-gallery-item.html
Labels: waiting on author

#1225 feat: add file size in resource list and resource pages
  base-theme/assets/css/main.scss
  base-theme/assets/css/variables.scss
  base-theme/assets/images/file_thumbnail.png
  base-theme/assets/images/pdf_thumbnail.png
  base-theme/assets/images/resource-download.svg
  base-theme/layouts/partials/content_header_v2.html
  base-theme/layouts/partials/file_size_formatter.html
  base-theme/layouts/partials/get_resource_category.html
  base-theme/layouts/partials/get_resource_download_link.html
  base-theme/layouts/partials/resource_body_v2.html
  course-v2/assets/css/course-resources.scss
  course-v2/assets/css/course-v2.scss
  course-v2/assets/css/resource-page-container.scss
  course-v2/assets/css/resource-page.scss
  course-v2/layouts/partials/get_resource_thumbnail_attributes.html
  course-v2/layouts/partials/resource_list.html
  course-v2/layouts/partials/resource_list_collapsible.html
  course-v2/layouts/partials/resource_list_item.html
  tests-e2e/ocw-ci-test-course/resource-list.spec.ts
Labels: needs review

#1264 fix long single word resource title going out of div
  course-v2/assets/css/course-resources.scss
Labels: needs review

#1257 perf: subset icon fonts
  README.md
  base-theme/assets/fonts/material-design-icons/MaterialIcons-Regular.codepoints
  base-theme/assets/fonts/material-design-icons/MaterialIcons-Regular.subset.codepoints
  base-theme/assets/fonts/material-design-icons/MaterialIcons-Regular.subset.ttf
  base-theme/assets/fonts/material-design-icons/MaterialIcons-Regular.subset.woff
  base-theme/assets/fonts/material-design-icons/MaterialIcons-Regular.subset.woff2
  base-theme/assets/fonts/material-design-icons/MaterialIcons-Regular.ttf
  base-theme/assets/fonts/material-design-icons/MaterialIcons-Regular.woff
  base-theme/assets/fonts/material-design-icons/MaterialIcons-Regular.woff2
  base-theme/assets/fonts/material-design-icons/MaterialIconsRound-Regular.codepoints
  base-theme/assets/fonts/material-design-icons/MaterialIconsRound-Regular.subset.codepoints
  base-theme/assets/fonts/material-design-icons/MaterialIconsRound-Regular.subset.woff2
  base-theme/assets/fonts/material-design-icons/MaterialIconsRound-Regular.woff2
  base-theme/assets/fonts/material-design-icons/README.md
  base-theme/assets/webpack/webpack.common.ts
  base-theme/layouts/partials/head.html
  package.json
  package_scripts/subset-fonts.ts
Labels: needs review, waiting on author
