Repository mitodl/ocw-hugo-themes, pull requests merged in 2024-03, with the labels that each got.

#1366 Fix resource list top border styling
  course-v2/layouts/lists/single.html
Labels: needs review, product:ocw

#1368 feat: adjust modal styles for `xs` screens
  base-theme/assets/css/modal.scss
Labels: waiting on author

#1369 Video pages layout width-fix
  base-offline/layouts/partials/video.html
  base-theme/assets/css/main.scss
  base-theme/assets/css/variables.scss
  base-theme/layouts/partials/video.html
  base-theme/layouts/partials/video_embed.html
  course-v2/assets/css/instructor-insights.scss
  course-v2/assets/css/video.scss
  course-v2/layouts/partials/course_content.html
Labels: needs review

#1374 Add back content class in course content
  course-v2/layouts/partials/course_content.html
Labels: waiting on author

#1373 Markdownify quiz choice
  course-v2/assets/css/course-v2.scss
  course-v2/layouts/partials/quiz_multiple_choice_choice.html
Labels: needs review
